apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: image-update-alert
  namespace: flux-system
spec:
  providerRef:
    name: app-webhook
  eventSeverity: info
  eventSources:
    - kind: ImagePolicy
      name: webhook-app-policy
      namespace: flux-system
