apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-webhook-flux-infra
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/hkaustav/webhook-flux-infra
  ref:
    branch: main
  secretRef:
    name: git-credentials