apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: simple-python-web-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simple-python-web-app
  policy:
    semver:
      range: ">=4.0.0"