apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: webhook-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: webhook-app-repo
  policy:
    semver:
      range: ">=4.0.0"