apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-resources
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters"
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-webhook-flux-infra
  targetNamespace: flux-system